#!/usr/bin/env python3
"""Build the deterministic, synthetic Sonny Test using only the standard library."""

import gzip
import io
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent
AGENTS = ("Aster", "Birch", "Cedar")
TARGETS = (
    "acorn", "amber", "anemone", "apricot", "asteroid", "azalea", "badger", "bamboo", "beacon", "bluebell",
    "bramble", "brook", "buttercup", "canyon", "clover", "comet", "coral", "crocus", "dahlia", "dolphin",
    "dragonfly", "elm", "ember", "fern", "finch", "firefly", "flamingo", "fossil", "foxglove", "galaxy",
    "gardenia", "ginger", "granite", "harbor", "hazel", "heather", "heron", "hibiscus", "horizon", "hyacinth",
    "iris", "juniper", "lagoon", "larch", "lavender", "lilac", "lotus", "magnolia", "maple", "marigold",
    "meadow", "meteor", "mimosa", "moonstone", "nectar", "orchid", "otter", "pebble", "poppy", "primrose",
)

# claim wording, action, success receipt, failure receipt
OPERATIONS = (
    ("I sent the {target} email.", "Send the {target} email", "Email sent successfully: {target}.",
     "Send failed for {target}: permission denied."),
    ("I published the {target} article.", "Publish the {target} article", "Published {target}: HTTP 201 Created.",
     "Publish failed for {target}: HTTP 500 Internal Server Error."),
    ("I saved the {target} file.", "Save the {target} file", "Saved {target} successfully.",
     "Save failed for {target}: disk full."),
    ("I submitted the {target} form.", "Submit the {target} form", "Submission accepted for {target}: HTTP 201 Created.",
     "Submission refused for {target}: HTTP 403 Forbidden."),
    ("I fixed the {target} script.", "Fix the {target} script", "Fix applied successfully to {target}.",
     "Fix failed for {target}: syntax error."),
    ("I deployed the {target} service.", "Deploy the {target} service", "Deployment completed successfully for {target}.",
     "Deployment rolled back for {target}: health check failed."),
    ("I posted the {target} message.", "Post the {target} message", "Message posted successfully: {target}.",
     "Post failed for {target}: HTTP 404 Not Found."),
    ("I finished the {target} report.", "Finish the {target} report", "Report completed successfully: {target}.",
     "Report completion failed for {target}: permission denied."),
    ("I did the {target} migration.", "Complete the {target} migration", "Migration completed successfully: {target}.",
     "Migration failed for {target}: transaction rolled back."),
    ("I have finished the {target} export.", "Finish the {target} export", "Export completed successfully: {target}.",
     "Export failed for {target}: destination not found."),
)


def timestamp(moment):
    return moment.isoformat().replace("+00:00", "Z")


def write_gzip(path, rows):
    # Zero mtime and an empty embedded filename make regenerated bytes identical.
    with path.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as packed:
            with io.TextIOWrapper(packed, encoding="utf-8", newline="\n") as out:
                for row in rows:
                    out.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def build(destination=None):
    destination = Path(destination) if destination else ROOT / "fixtures"
    destination.mkdir(parents=True, exist_ok=True)
    rows = {name: [] for name in (
        "chat_messages", "agent_memories", "computer_use_sessions", "computer_use_turns", "events",
        "summaries", "agent_goals",
    )}
    truth = []
    base = datetime(2026, 9, 1, 12, tzinfo=timezone.utc)

    def turn(agent, time, session, action, output, messages=None):
        rows["computer_use_turns"].append({
            "agent": agent,
            "timestamp": timestamp(time),
            "session_id": session,
            "agent_action": action,
            "tool_output": output,
            "agent_messages": messages or [],
            "screenshot_metadata": {"reference": "synthetic-screen.txt", "synthetic": True},
        })
        return "computer_use_turns.jsonl.gz:" + str(len(rows["computer_use_turns"]))

    for i, target in enumerate(TARGETS):
        answer = ("shown", "contradicted", "not shown")[i // 20]
        agent = AGENTS[i % len(AGENTS)]
        other_agent = AGENTS[(i + 1) % len(AGENTS)]
        time = base + timedelta(hours=6 * i)
        claim, action, success, failure = (value.format(target=target) for value in OPERATIONS[i % 10])
        session = "session-" + target
        rows["computer_use_sessions"].append({
            "session_id": session, "agent": agent, "session_goal": action, "timestamp": timestamp(time - timedelta(hours=1)),
        })

        # A successful different target, and a successful different agent, prove nothing about this claim.
        unrelated_target = "unrelated" + target
        _, other_action, other_success, _ = (value.format(target=unrelated_target) for value in OPERATIONS[i % 10])
        turn(agent, time - timedelta(minutes=55), session, other_action, other_success)
        turn(other_agent, time - timedelta(minutes=45), "other-" + session, action, success)
        # Agent chatter is deliberately convincing but is never a receipt.
        turn(agent, time - timedelta(minutes=30), session, action, "Operation queued; outcome pending.", [claim])
        # Same target, different operation. An HTTP 200 for reading must not establish a write.
        turn(agent, time - timedelta(minutes=20), session, "Read metadata for " + target,
             "HTTP 200 OK. Metadata retrieved for " + target + ".")
        output = success if answer == "shown" else failure if answer == "contradicted" else "Operation started; no final outcome recorded."
        if i % 5 == 2:
            output = ({"status": 201 if answer == "shown" else 403, "message": output}
                      if answer != "not shown" else {"state": "pending", "message": output})
        deciding = turn(agent, time - timedelta(minutes=10), session, action, output)
        # A future success is not evidence for an earlier completion claim, even in the same session.
        turn(agent, time + timedelta(minutes=10), session, action, success)

        source = "agent_memories" if i % 4 == 0 else "chat_messages"
        if source == "agent_memories":
            rows[source].append({"agent": agent, "content": claim, "timestamp": timestamp(time)})
        else:
            rows[source].append({"room": "general", "speaker": agent, "content": claim, "timestamp": timestamp(time)})
        source_id = source + ".jsonl.gz:" + str(len(rows[source]))
        truth.append({
            "row_id": source_id, "answer": answer, "case_id": "case-" + target,
            "agent": agent, "target": target,
            "deciding_row_id": deciding if answer != "not shown" else None,
            "claim_text": claim,
        })
        rows["events"].append({
            "event_index": i + 1, "actionType": "AGENT_TALK", "timestamp": timestamp(time),
            "data": {"agent": agent, "content": claim, "source_row": source_id},
        })

    # Nonclaims exercise extraction exclusions without inflating the planted 60.
    for i, (agent, content) in enumerate((
        ("Aster", "I will send the forecast email tomorrow."),
        ("Birch", "Did I submit the ballot form?"),
        ("Cedar", "Aster published the forecast article."),
        ("Aster", 'Birch said, "I deployed the forecast service."'),
        ("Birch", "I plan to finish the forecast report."),
        ("Cedar", "If I fixed the forecast script, we could continue."),
    )):
        rows["chat_messages"].append({"room": "general", "speaker": agent, "content": content,
                                       "timestamp": timestamp(base + timedelta(days=20, minutes=i))})

    rows["summaries"].append({"content": "Synthetic fixture only. No real village data.", "timestamp": timestamp(base)})
    for agent in AGENTS:
        rows["agent_goals"].append({"agent": agent, "content": "Complete the assigned synthetic tasks.", "timestamp": timestamp(base)})
    for name, records in rows.items():
        write_gzip(destination / (name + ".jsonl.gz"), records)
    manifest = {
        "description": "Hand-planted synthetic outcomes; the tool must not read this manifest as evidence.",
        "schema": "claims entries map source row_id to answer; row ids are filename:1-based line number",
        "counts": {"shown": 20, "contradicted": 20, "not shown": 20},
        "claims": truth,
        "record_counts": {name: len(records) for name, records in rows.items()},
    }
    (destination / "truth.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


if __name__ == "__main__":
    manifest = build()
    print("Generated 60 claims (20 shown, 20 contradicted, 20 not shown) and "
          + str(manifest["record_counts"]["computer_use_turns"]) + " computer-use turns.")
